ENCODER_ENABLE = yes
CONSOLE_ENABLE = no
EXTRAKEY_ENABLE = yes
VIA_ENABLE = yes
VIAL_ENABLE = yes
VIAL_ENCODERS_ENABLE = yes
LTO_ENABLE = yes

RGBLIGHT_ENABLE = no

RGB_MATRIX_ENABLE = yes
RGB_MATRIX_DRIVER=WS2812
VIALRGB_ENABLE = yes

BOTMAGIC_ENABLE = no
MAGIC_ENABLE = no


QMK_SETTINGS = no
MOUSEKEY_ENABLE = no

OLED_ENABLE = yes
OLED_DRIVER = SSD1306

COMBO_ENABLE = no
KEY_OVERRIDE_ENABLE = no
TAP_DANCE_ENABLE = no